### ISSUE TITLE
Cannot find module '@chatereum/react-e2ee'

### ISSUE THREAD

**Issue by Clid3** [Arjis2020/react-e2ee#2]
![Screenshot from 2024-01-14 10-46-41](https://github.com/Arjis2020/react-e2ee/assets/30189267/90f68be9-c3c8-4f3b-aa1c-8660fb8f68ce)

**Comment by Arjis2020** [comment]
Did you install it using npm?
If not, run `npm i @chatereum/react-e2ee`

**Comment by Clid3** [comment]
> Did you install it using npm? If not, run `npm i @chatereum/react-e2ee`

yes, before raising this issue, I did installed the package using npm. 
![Screenshot from 2024-01-15 15-33-19](https://github.com/Arjis2020/react-e2ee/assets/30189267/89d9fdb0-e1e0-4bb1-8d75-196270436a16)

**Comment by Arjis2020** [comment]
@Clid3 Can I have a look at your `tsconfig.json`?

**Comment by Clid3** [comment]
> @Clid3 Can I have a look at your `tsconfig.json`?

![Uploading Screenshot from 2024-01-16 16-50-57.png…]()

**Comment by Clid3** [comment]
> @Clid3 Can I have a look at your `tsconfig.json`?

![Screenshot from 2024-01-16 16-50-57](https://github.com/Arjis2020/react-e2ee/assets/30189267/a5bfc2b5-7955-48e3-bcc9-8f47668218af)

**Comment by DennisRono** [comment]
![Screenshot 2024-01-30 120703](https://github.com/Arjis2020/react-e2ee/assets/72130813/2b5a5561-4007-4e03-8a53-d81942625d98)
i am also having the same issue

**Comment by Arjis2020** [comment]
@Clid3 @DennisRono After some extensive debugging, I figured it was due to the `bin` folder (the build folder for this TypeScript project) not getting published to NPM and therefore, if you check your `node_modules` directory, the `bin` folder containing the final build of the project is not present. Hence, the error.

This has now been fixed in version `3.0.1`. Request you to upgrade your dependency.
